### PR TITLE
Added boilerplate code and initial files

### PR DESCRIPTION
**Pull request by Suriya-2002**
- Added boilerplate code
- Added reset CSS
- Created basic folder structure

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@Suriya-2002 For `assets/icons/fontAwesome.js`, use the CDN. Check [cdnjs](https://cdnjs.com).

**Comment by aravindvnair99** [comment]
@newb-dev-1008 add him into the repo. That's better as the checks can run properly without throwing errors. @Suriya-2002 PR from this repo itself.

**Comment by newb-dev-1008** [comment]
> @newb-dev-1008 add him into the repo. That's better as the checks can run properly without throwing errors. @Suriya-2002 PR from this repo itself.

Cool, @Suriya-2002 check your e-mail, I've sent an invite to join the organization as a member (Web Development team). The other two still have their outside collaborator invites pending, once they join in I'll add them as members too.

**Comment by Suriya-2002** [comment]
> @newb-dev-1008 add him into the repo. That's better as the checks can run properly without throwing errors. @Suriya-2002 PR from this repo itself.

Alright, will do it from next PR.

**Comment by Suriya-2002** [comment]
> > @newb-dev-1008 add him into the repo. That's better as the checks can run properly without throwing errors. @Suriya-2002 PR from this repo itself.
> 
> Cool, @Suriya-2002 check your e-mail, I've sent an invite to join the organization as a member (Web Development team). The other two still have their outside collaborator invites pending, once they join in I'll add them as members too.

Yeah, got it.

**Review by aravindvnair99 — APPROVED** [review]

**Review by aravindvnair99 — APPROVED** [review]

**Review by aravindvnair99 — APPROVED** [review]

**Pull request merged**
